spring.application.name=showtime-gateway
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=movie-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://movie-service:8082
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/movies/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1